// constants/waters.ts

import { Water } from "@/types/water";

export const waters: Water[] = [
  {
    name: "Volvic",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Volvic",
        location: "Volvic (Puy-de-Dôme)",
        composition: {
          calcium: 12,
          magnesium: 8,
          sodium: 30,
          potassium: 6,
          bicarbonates: 74,
          sulfates: 9,
          chlorures: 15,
          fluorures: 0,
          silice: 0,
          nitrate: 7.3,
          residu: 130,
          ph: 7,
        },
      },
    ],
  },
  {
    name: "Evian",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Evian",
        location: "Évian-les-Bains (Haute-Savoie)",
        composition: {
          calcium: 80,
          magnesium: 26,
          sodium: 6.5,
          potassium: 1,
          bicarbonates: 360,
          sulfates: 14,
          chlorures: 10,
          fluorures: 0,
          silice: 15,
          nitrate: 3.8,
          residu: 309,
          ph: 7.2,
        },
      },
    ],
  },
  {
    name: "Wattwiller",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Wattwiller",
        location: "Wattwiller (Vosges)",
        composition: {
          calcium: 35,
          magnesium: 11,
          sodium: 3.2,
          potassium: 1,
          bicarbonates: 135,
          sulfates: 24,
          chlorures: 0,
          fluorures: 0.5,
          silice: 0,
          nitrate: 0,
          residu: 155,
          ph: 7.5,
        },
      },
    ],
  },
  {
    name: "Thonon",
    category: "eau de source",
    subcategory: "plate",
    sources: [
      {
        name: "Source Thonon",
        location: "Thonon-les-Bains (Haute-Savoie)",
        composition: {
          calcium: 92,
          magnesium: 16,
          sodium: 6,
          potassium: 1,
          bicarbonates: 340,
          sulfates: 12,
          chlorures: 14,
          fluorures: 0,
          silice: 0,
          nitrate: 8,
          residu: 340,
          ph: 7.4,
        },
      },
    ],
  },
  {
    name: "Contrex",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Contrex",
        location: "Contrexéville (Vosges)",
        composition: {
          calcium: 468,
          magnesium: 74.5,
          sodium: 1,
          potassium: 0,
          bicarbonates: 372,
          sulfates: 0,
          chlorures: 0,
          fluorures: 0,
          silice: 0,
          nitrate: 0,
          residu: 2078,
          ph: 7.4,
        },
      },
    ],
  },
  {
    name: "Mont Roucous",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Mont Roucous",
        location: "Lacaune-les-Bains (Tarn)",
        composition: {
          calcium: 2.4,
          magnesium: 0.5,
          sodium: 10,
          potassium: 0.4,
          bicarbonates: 6.3,
          sulfates: 3,
          chlorures: 3,
          fluorures: 0.01,
          silice: 8.2,
          nitrate: 0.3,
          residu: 25,
          ph: 5.85,
        },
        benefits: [
          "Convient aux nourrissons",
          "Idéale pour les reins fragiles",
          "Faible minéralisation",
        ],
      },
    ],
  },
  {
    name: "Celtic",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Celtic",
        location: "Niederbronn-les-Bains (Bas-Rhin)",
        composition: {
          calcium: 10.5,
          magnesium: 4,
          sodium: 1.1,
          potassium: 1.9,
          bicarbonates: 48,
          sulfates: 6,
          chlorures: 5,
          fluorures: 0.1,
          silice: 0,
          nitrate: 2.1,
          residu: 50,
          ph: 7.5,
        },
      },
    ],
  },
  {
    name: "Abatilles",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Abatilles",
        location: "Arcachon (Gironde)",
        composition: {
          calcium: 19,
          magnesium: 9,
          sodium: 100,
          potassium: 4,
          bicarbonates: 127,
          sulfates: 8,
          chlorures: 137,
          fluorures: 0,
          silice: 0,
          nitrate: 0,
          residu: 354,
          ph: 8.2,
        },
      },
    ],
  },
  {
    name: "Badoit",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source Badoit",
        location: "Saint-Galmier (Loire)",
        composition: {
          calcium: 153,
          magnesium: 80,
          sodium: 0,
          potassium: 11,
          bicarbonates: 125,
          sulfates: 3.5,
          chlorures: 54,
          fluorures: 1.2,
          silice: 2.7,
          nitrate: 0,
          residu: 1100,
          ph: 6,
        },
      },
    ],
  },
  {
    name: "Rozana",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source Rozana",
        location: "Vichy (Auvergne)",
        composition: {
          calcium: 301,
          magnesium: 160,
          sodium: 493,
          potassium: 52,
          bicarbonates: 1837,
          sulfates: 230,
          chlorures: 649,
          fluorures: 1,
          silice: 97,
          nitrate: 1,
          residu: 3022,
          ph: 6.3,
        },
      },
    ],
  },
  {
    name: "Vittel",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Vittel",
        location: "Vittel (Vosges)",
        composition: {
          calcium: 240,
          magnesium: 42,
          sodium: 5.2,
          potassium: 0,
          bicarbonates: 384,
          sulfates: 400,
          chlorures: 0,
          fluorures: 0,
          silice: 0,
          nitrate: 4.4,
          residu: 1084,
          ph: 0,
        },
      },
    ],
  },
  {
    name: "Quézac",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source Quézac",
        location: "Quézac (Lozère)",
        composition: {
          calcium: 165,
          magnesium: 69,
          sodium: 110,
          potassium: 32.6,
          bicarbonates: 1000,
          sulfates: 0,
          chlorures: 0,
          fluorures: 2.2,
          silice: 0,
          nitrate: 0,
          residu: 980,
          ph: 5.8,
        },
      },
    ],
  },
  {
    name: "Perrier",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source Perrier",
        location: "Vergèze (Gard)",
        composition: {
          calcium: 150,
          magnesium: 3.9,
          sodium: 9.6,
          potassium: 1,
          bicarbonates: 420,
          sulfates: 25.3,
          chlorures: 19.5,
          fluorures: 0,
          silice: 0,
          nitrate: 7.3,
          residu: 45,
          ph: 5.5,
        },
      },
    ],
  },
  {
    name: "San Pellegrino",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source San Pellegrino",
        location: "San Pellegrino Terme (Italie)",
        composition: {
          calcium: 164,
          magnesium: 49.5,
          sodium: 31.2,
          potassium: 2.2,
          bicarbonates: 0,
          sulfates: 0,
          chlorures: 49.4,
          fluorures: 0.5,
          silice: 7.1,
          nitrate: 2.9,
          residu: 854,
          ph: 7.7,
        },
      },
    ],
  },
  {
    name: "Hépar",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Hépar",
        location: "Vittel (Vosges)",
        composition: {
          calcium: 549,
          magnesium: 119,
          sodium: 0,
          potassium: 0,
          bicarbonates: 383.7,
          sulfates: 1530,
          chlorures: 0,
          fluorures: 0,
          silice: 0,
          nitrate: 4.3,
          residu: 2513,
          ph: 0,
        },
      },
    ],
  },
  {
    name: "Velleminfroy",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Velleminfroy",
        location: "Velleminfroy (Haute-Saône)",
        composition: {
          calcium: 510,
          magnesium: 66,
          sodium: 10.3,
          potassium: 2.6,
          bicarbonates: 322,
          sulfates: 1400,
          chlorures: 3.2,
          fluorures: 0,
          silice: 0,
          nitrate: 0,
          residu: 2420,
          ph: 7.4,
        },
      },
    ],
  },
  {
    name: "Montcalm",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Montcalm",
        location: "Pyrénées ariégeoises",
        composition: {
          calcium: 3,
          magnesium: 0.7,
          sodium: 6,
          potassium: 0.6,
          bicarbonates: 5.2,
          sulfates: 10,
          chlorures: 0.6,
          fluorures: 0.1,
          silice: 7.5,
          nitrate: 0.7,
          residu: 32,
          ph: 6.8,
        },
      },
    ],
  },
  {
    name: "Vichy Célestins",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source Vichy Célestins",
        location: "Vichy (Allier)",
        composition: {
          calcium: 103,
          magnesium: 10,
          sodium: 1172,
          potassium: 66,
          bicarbonates: 298.9,
          sulfates: 138,
          chlorures: 235,
          fluorures: 1.5,
          silice: 0,
          nitrate: 0,
          residu: 3325,
          ph: 6.8,
        },
      },
    ],
  },
  {
    name: "La Salvetat",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source La Salvetat",
        location: "La Salvetat-sur-Agout (Hérault)",
        composition: {
          calcium: 160,
          magnesium: 7.5,
          sodium: 5,
          potassium: 2,
          bicarbonates: 53,
          sulfates: 20,
          chlorures: 5,
          fluorures: 0,
          silice: 5.5,
          nitrate: 0,
          residu: 520,
          ph: 6,
        },
      },
    ],
  },
  {
    name: "Puits Saint Georges",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sources: [
      {
        name: "Source Puits Saint Georges",
        location: "Saint-Yorre (Allier)",
        composition: {
          calcium: 44.7,
          magnesium: 33.6,
          sodium: 1125,
          potassium: 18.7,
          bicarbonates: 1423,
          sulfates: 0,
          chlorures: 39,
          fluorures: 0,
          silice: 0,
          nitrate: 0,
          residu: 0,
          ph: 6,
        },
      },
    ],
  },
  {
    name: "Courmayeur",
    category: "eau minérale",
    subcategory: "plate",
    sources: [
      {
        name: "Source Courmayeur",
        location: "Val d’Aoste (Italie)",
        composition: {
          calcium: 57.6,
          magnesium: 5.2,
          sodium: 0,
          potassium: 0.18,
          bicarbonates: 17,
          sulfates: 141.2,
          chlorures: 0.03,
          fluorures: 0.1,
          silice: 0,
          nitrate: 0.2,
          residu: 2133,
          ph: 7.7,
        },
      },
    ],
  },
  {
    name: "Cristaline",
    category: "eau de source",
    subcategory: "plate",
    sources: [
      {
        name: "Source Roxane",
        location: "Verdun-sur-Garonne",
        composition: {
          calcium: 45,
          magnesium: 5,
          sodium: 2,
          potassium: 1,
          bicarbonates: 120,
          sulfates: 5,
          chlorures: 4,
          fluorures: 0.1,
          silice: 10,
          nitrate: 3,
          residu: 150,
          ph: 7.2,
        },
      },
      {
        name: "Source Clairvaux",
        location: "Clairvaux-les-Lacs",
        composition: {
          calcium: 50,
          magnesium: 3,
          sodium: 1,
          potassium: 1,
          bicarbonates: 90,
          sulfates: 6,
          chlorures: 2,
          fluorures: 0.2,
          silice: 8,
          nitrate: 2,
          residu: 140,
          ph: 6.9,
        },
      },
      {
        name: "Source Ste-Sophie",
        location: "Châteauneuf-les-Martigues",
        composition: {
          calcium: 48,
          magnesium: 4,
          sodium: 2,
          potassium: 1,
          bicarbonates: 110,
          sulfates: 8,
          chlorures: 3,
          fluorures: 0.15,
          silice: 9,
          nitrate: 4,
          residu: 160,
          ph: 7.3,
        },
      },
    ],
  },
];
