// constants/waters.ts

import type { WaterBrand } from "@/types/water";

export const waters: WaterBrand[] = [
  {
    name: "Volvic",
    category: "eau minérale",
    subcategory: "plate",
    sourceLocation: "Volvic (Puy-de-Dôme)",
    dryResidue: 130,
    pH: 7,
    sodium: 30,
    calcium: 12,
    magnesium: 8,
    potassium: 6,
    bicarbonates: 74,
    chlorides: 15,
    sulfates: 9,
    nitrates: 7.3,
    silicates: 0,
    fluorides: 0,
  },
  {
    name: "Cristaline",
    category: "eau de source",
    subcategory: "plate",
    sourceLocation: "variable (plusieurs sources)",
    dryResidue: 200,
    pH: 7.2,
    calcium: 30,
    magnesium: 5,
    sodium: 4,
  },
  {
    name: "Saint-Yorre",
    category: "eau minérale",
    subcategory: "gazeuse naturelle",
    sourceLocation: "Saint-Yorre (Allier)",
    dryResidue: 4774,
    pH: 6.6,
    sodium: 1708,
    calcium: 90,
    magnesium: 11,
    potassium: 110,
    bicarbonates: 4370,
    chlorides: 322,
    fluorides: 1.5,
    sulfates: 174,
    silicates: 0,
    nitrates: 0,
  },
  {
    name: "Evian",
    category: "eau minérale",
    subcategory: "plate",
    sourceLocation: "Évian-les-Bains (Haute-Savoie)",
    pH: 7.2,
    dryResidue: 309,
    calcium: 80,
    magnesium: 26,
    potassium: 1,
    sodium: 6.5,
    nitrates: 3.8,
    bicarbonates: 360,
    fluorides: 0,
    sulfates: 14,
    silicates: 15,
    chlorides: 10,
  },
  {
    name: "Wattwiller",
    category: "eau minérale",
    subcategory: "plate",
    sourceLocation: "Wattwiller (Vosges)",
    dryResidue: 155,
    pH: 7.5,
    sodium: 3.2,
    calcium: 35,
    magnesium: 11,
    potassium: 1,
    bicarbonates: 135,
    sulfates: 24,
    chlorides: 0,
    silicates: 0,
    fluorides: 0.5,
    nitrates: 0,
  },
  {
    name: "Mont Blanc",
    category: "eau de source",
    subcategory: "plate",
    sourceLocation: "à compléter",
    dryResidue: 134,
    pH: 7.3,
    sodium: 5,
    calcium: 380,
    magnesium: 30,
    potassium: 21,
    bicarbonates: 700,
    sulfates: 500,
    chlorides: 10,
    silicates: 0,
    fluorides: 10,
    nitrates: 10,
  },
  {
    name: "Contrex",
    category: "eau minérale",
    subcategory: "plate",
    sourceLocation: "Contrexéville (Vosges)",
    dryResidue: 2078,
    pH: 7.4,
    sodium: 1,
    calcium: 468,
    magnesium: 74.5,
    potassium: 0,
    bicarbonates: 372,
    chlorides: 0,
    fluorides: 0,
  },
];
